version: '3.7'

volumes:
    mysql:
    upload: {}
    log:

services: 
    mysql:
        image: mysql:5.7
        restart: always
        ports: 
            - "3306:3306"

        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD:
        volumes: 
            - "mysql:/var/lib/mysql:rw"
        expose: 
            - "3306"
    apache:
        build: .
        environment: 
            MYSQL_CONNECTION_STRING: "mysql,root,,3306"
        ports:
            - "80:80"
        volumes:
            - "./dist:/var/www/html/"
            - "upload:/var/www/upload/"
            - "log:/var/log/app"
            - "./server/scripts:/scripts"
        expose: 
            - "80"
  
