# This is a basic workflow to help you get started with Actions

name: Docker Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: NPM and COMPOSER insalling
      run: |
        npm install
        composer install

    - name: NPM build
      run: npm run build

    - name: Building docker image
      run: docker build -t apptemp .

    - name: Docker Login
      env:
        DOCKER_USER: ${{ github.actor }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: echo -p $DOCKER_TOKEN | docker login docker.pkg.github.com -u $DOCKER_USER --password-stdin

    - name: Docker push
      run: |
        docker tag apptemp docker.pkg.github.com/haan78/repo/apptemp:1.0 
        docker push docker.pkg.github.com/haan78/repo/apptemp:1.0
      
      